# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: tester
      POSTGRES_DB: default
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./pgconf.conf:/etc/postgresql/postgresql.conf:ro
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025 # Web UI. Reach via http://localhost:8025
      - 1025:1025 # SMTP server
  searxng:
    image: searxng/searxng:2026.2.6-b5bb27f23
    ports:
      - 6148:8080
    volumes:
      - ./searxng:/etc/searxng:rw
  seaweedfs:
    image: chrislusf/seaweedfs:3.75
    command: server -s3 -ip.bind=0.0.0.0 -s3.port=8333
    ports:
      - 8333:8333
  dev:
    image: alpine:3.22
    depends_on:
      - db
      - redis
      - mailhog
      - searxng
      - xinity-infoserver
      - seaweedfs
volumes:
  pgdata:
