export const TEST_ENV = {
  DB_CONNECTION_URL: "postgresql://localhost/test",
  XINITY_SECRET_KEY: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  REDIS_URL: "redis://localhost:6379",
  INFOSERVER_URL: "http://localhost:3000",
  INFOSERVER_CACHE_TTL_MS: "30000",
  WEB_SEARCH_ENGINE_URL: "http://localhost:6148/",
  LOAD_BALANCE_STRATEGY: "random",
  LOG_LEVEL: "info",
  DEEP_RESEARCH_MAX_STEPS: "5",
  DEEP_RESEARCH_COMPACTION_THRESHOLD: "0.5",
};
